# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 18:59
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modify', models.DateTimeField(auto_now=True)),
                ('position', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Місце розташування')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('type', models.CharField(choices=[('hotel', 'Готель'), ('cafe', 'Заклад харчування'), ('monument', "Архітектурна пам'ятка"), ('other', 'Інше')], db_index=True, default='other', max_length=15)),
                ('main_img', models.ImageField(upload_to='markers/', verbose_name='Головне зображення')),
                ('description', models.TextField(max_length=1600, verbose_name='Опис')),
                ('address', models.CharField(max_length=255, verbose_name='Адреса')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='marker.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='marker.Country')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
