# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 20:09
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marker', '0004_auto_20170430_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='city',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='country',
        ),
        migrations.AlterField(
            model_name='marker',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, verbose_name='Місце розташування'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
