# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 13:43
from __future__ import unicode_literals

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marker', '0007_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=apps.core.utils.upload_directory_path, verbose_name='Зображення'),
        ),
    ]
